name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    
    - name: Build SP app
      run: ./mvnw package && java -jar target/product-service-0.0.1-SNAPSHOT.jar
    - name: Build the Docker image
      run: |
          cd productservice
          docker build -t alpha-service/product-service .
